# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Princeton Data Science 
tagline:             'Blog'
description:         'We hope to create a community of students interested in data science careers, and to provide opportunities to sharpen data-oriented skills.'
url:                 http://www.princeton.edu/~datasci/
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Francine Camacho 
  url:               frcamacho@github.io
  email:             datasci@princeton.edu

# Custom vars
version:             1.1.0

# Liquid-LaTeX plugin
liquid_latex:
  debug: false
  density: 300
  usepackages: pst-all,pst-3dplot
  output_directory: /res/latex
  latex_cmd: "latex -interaction=nonstopmode $texfile &> /dev/null"
  dvips_cmd: "dvips -E $dvifile -o $epsfile &> /dev/null"
  convert_cmd: "convert -density $density $epsfile $pngfile &> /dev/null"
  temp_filename: "latex_temp"

gems:
  - liquid_latex
  